### PR TITLE
Radix initialization

### PR DESCRIPTION
**Pull request by twodayslate**
Duplication of #24, to finish off the work by @bpolania

- [x] bug fixes
- [x] spacing fixed
- [x] README
- [x] Prefix support
- [x] More test cases

### CODE REVIEW

**Comment by twodayslate** [comment]
Should probably do a metric on what String init method is faster (current or radix: 10). Curious.

**Comment by mkrd** [comment]
Looks good, I'll merge it. What do you exaclty mean by "do a metric on what String init method is faster" ?

**Comment by twodayslate** [comment]
BInt(String)? vs BInt(String, radix: 10)?

If BInt(String, radix: 10)? is faster than BInt(String)? then there is no point in having BInt(String). If it is slower than we can call BInt(String)? when radix is 10. 

I will do this in my next PR.

**Comment by twodayslate** [comment]
BInt(String)? is 4-5 times faster than BInt(String, radix: 10)? Same goes for BDouble

**Pull request merged**
